#!/bin/sh
#Assemble html file to printout memory verses.


verse1Ref="John 1:12"
verse1Translation="ESV"
verse1Text="But to all who did receive him, who believed in his name, he gave the right to become children on God,"
#            "
verse1Adjustments="-"


verse2Ref="Psalm 139:14"
verse2Translation="ESV"
verse2Text="I praise you, for I am fearfully and wonderfully made. Wonderful are your works; my soul knows it very well."
#            "I praise you, for I am fearfully and wonderfully made. Wonderful are your works; my soul knows it very well." (Psalm 139:14)
verse2Adjustments="-"

verse3Ref="Psalm 86:15"
verse3Translation="ESV"
verse3Text="But you, O Lord, are a God merciful and gracious, slow to anger and abounding in steadfast love and faithfulness."
#          "But you, O Lord, are a God merciful and gracious, slow to anger and abounding in steadfast love and faithfulness." (Psalm 86:15)
verse3Adjustments="-"

verse4Ref="Ephesians 4:32"
verse4Translation="ESV"
verse4Text="Be kind to one another, tenderhearted, forgiving one another, as God in Christ forgave you."
#          "Be kind to one another, tenderhearted, forgiving one another, as God in Christ forgave you." (Ephesians 4:32)
verse4Adjustments="-"

verse5Ref="Romans 8:38-39"
verse5Translation="ESV"
verse5Text="For I am sure that neither death nor life, nor angels nor rulers, nor things present nor things to come, nor powers, nor height nor depth, nor anything else in all creation, will be able to separate us from the love of God in Christ Jesus our Lord."
#          "For I am sure that neither death nor life, nor angels nor rulers, nor things present nor things to come, nor powers, nor height nor depth, nor anything else in all creation, will be able to separate us from the love of God in Christ Jesus our Lord." (Romans 8:38-39)
verse5Adjustments=""


verse6Ref="Psalm 19:1"
verse6Translation="ESV"
verse6Text="The heavens declare the glory of God, and the sky above proclaims his handiwork."
#           The heavens declare the glory of God, and the sky above proclaims his handiwork.
verse6Adjustments="-"


main() {
	oFile='../1.html' #name for output file. Save in parent folder assuming most folks don't want to read shell script.
	title='Memory Verses, 1 Gods Love - Hope for the outcast (ver 2)'

	case $1 in
		"a") #assemble a html file with the memory verses variable above
		if [ -f "$oFile" ]; then rm "$oFile"; fi #remove any old file if present.
		printf "<!DOCTYPE html>" >> $oFile
		printf "\n<html><head>" >> $oFile
		printf "\n<title>%s</title>" "$title" >> $oFile
		printf "\n</head><body>" >> $oFile

		printf "\n<table border=\"1\">" >> $oFile
			printf "\n<caption>%s</caption>" "$title" >> $oFile
			printf "\n<tr>" >> $oFile
			printf "\n\t<th>Reference</th>" >> $oFile
			printf "\n\t<th>Text</th>" >> $oFile
			printf "\n\t</tr>" >> $oFile
			makeRow "$verse1Ref" "$verse1Text" "$oFile"
			makeRow "$verse2Ref" "$verse2Text" "$oFile"
			makeRow "$verse3Ref" "$verse3Text" "$oFile"
			makeRow "$verse4Ref" "$verse4Text" "$oFile"
			makeRow "$verse5Ref" "$verse5Text" "$oFile"
			makeRow "$verse6Ref" "$verse6Text" "$oFile"
			printf "\n</table>" >> $oFile
		printf "\n<hr>" >> $oFile
		
		printf "\n<table border=\"1\">" >> $oFile
			printf "\n<caption>%s</caption>" "$title" >> $oFile
			printf "\n<tr>" >> $oFile
			printf "\n\t<th>Reference</th>" >> $oFile
			printf "\n\t<th>Text</th>" >> $oFile
			printf "\n\t</tr>" >> $oFile
			makeRow "$verse1Ref" "$verse1Text" "$oFile"
			makeRow "$verse2Ref" "$verse2Text" "$oFile"
			makeRow "$verse3Ref" "$verse3Text" "$oFile"
			makeRow "$verse4Ref" "$verse4Text" "$oFile"
			makeRow "$verse5Ref" "$verse5Text" "$oFile"
			makeRow "$verse6Ref" "$verse6Text" "$oFile"
			printf "\n</table>" >> $oFile
		printf "\n<hr>" >> $oFile
		
		printf "\n<table border=\"1\">" >> $oFile
			printf "\n<caption>%s</caption>" "$title" >> $oFile
			printf "\n<tr>" >> $oFile
			printf "\n\t<th>Reference</th>" >> $oFile
			printf "\n\t<th>Text</th>" >> $oFile
			printf "\n\t</tr>" >> $oFile
			makeRow "$verse1Ref" "$verse1Text" "$oFile"
			makeRow "$verse2Ref" "$verse2Text" "$oFile"
			makeRow "$verse3Ref" "$verse3Text" "$oFile"
			makeRow "$verse4Ref" "$verse4Text" "$oFile"
			makeRow "$verse5Ref" "$verse5Text" "$oFile"
			makeRow "$verse6Ref" "$verse6Text" "$oFile"
			printf "\n</table>" >> $oFile

		printf "\n</body></html>" >> $oFile

		;;
		"sp") #Catch some typos, spelling errors. Uncertain best among several spell checkers, aspell, hunspell, etc. Just pick one
			hunspell $oFile #othr spell checkers - aspell, etc.
			;;

      "uc") #check for unicode
	  	#unicode may have lots of benefits, but some legacy software tools that only do ASCII might crash if reading a unicode.
		#For example, ascii tools my want straight quotes and not curly quotes.
        grep -rnoP "[^\x00-\x7F]" "$oFile" #n option for line number
	  ;;
		*)
			printf 'unexpected argument %s, plz try again' "$1"
			exit 1
			;;
	esac
 	exit 0
 } #end details


makeRow() {
	printf "\n<tr>" >> $oFile
		printf "\n\t<td>%s</td>" "$1" >> "$3"
		printf "\n\t<td>%s</td>" "$2" >> "$3"
		printf "\n\t</tr>" >> $oFile
}

main "$@"; exit

