#!/bin/sh
#Assemble html file to printout memory verses.


verse1Ref="Proverbs 3:5"
verse1Translation="ESV"
verse1Text="\"Trust in the Lord with all your heart, and do not lean on your own understanding.\""
#            "Trust in the Lord with all your heart, and do not lean on your own understanding." (Proverbs 3:5)
verse1Adjustments="-"

verse2Ref="Proverbs 3:6"
verse2Translation="ESV"
verse2Text="In all your ways acknowledge him, and he will make straight your paths."
#          "In all your ways acknowledge him, and he will make straight your paths." (Proverbs 3:6)
verse2Adjustments="-"

verse3Ref="1 Corinthians 15:57"
verse3Translation="ESV"
verse3Text="But thanks be to God, who gives us the victory through our Lord Jesus Christ."
#          "But thanks be to God, who gives us the victory through our Lord Jesus Christ." (1 Corinthians 15:57)
verse3Adjustments="-"

verse4Ref="1 Corinthians 15:58"
verse4Translation="ESV"
verse4Text="Therefore, my beloved brothers, be steadfast, immovable, always abounding in the work of the Lord, knowing that in the Lord your labor is not in vain."
#          "Therefore, my beloved brothers, be steadfast, immovable, always abounding in the work of the Lord, knowing that in the Lord your labor is not in vain." (1 Corinthians 15:58)
verse4Adjustments="-"

verse5Ref="Proverbs 3:5-6"
verse5Translation="ESV"
verse5Text="see first 2 verses"
#
verse5Adjustments="repeat first 2 verses"


main() {
	oFile='../3.html' #random name for output file
	title='Memory Verses, 3 Gods Faithfulness - Return to Canaan (ver 2)'

	case $1 in
		"a") #assemble a html file with the memory verses
		if [ -f "$oFile" ]; then rm "$oFile"; fi #remove any old file if present.
		printf "<!DOCTYPE html>" >> $oFile
		printf "\n<html><head>" >> $oFile
		printf "\n<title>%s</title>" "$title" >> $oFile
		printf "\n</head><body>" >> $oFile

		printf "\n<table border=\"1\">" >> $oFile
			printf "\n<caption>%s</caption>" "$title" >> $oFile
			printf "\n<tr>" >> $oFile
			printf "\n\t<th>Reference</th>" >> $oFile
			printf "\n\t<th>Text</th>" >> $oFile
			printf "\n\t</tr>" >> $oFile
			makeRow "$verse1Ref" "$verse1Text" "$oFile"
			makeRow "$verse2Ref" "$verse2Text" "$oFile"
			makeRow "$verse3Ref" "$verse3Text" "$oFile"
			makeRow "$verse4Ref" "$verse4Text" "$oFile"
			makeRow "$verse5Ref" "$verse5Text" "$oFile"
			printf "\n</table>" >> $oFile
		printf "\n<hr>" >> $oFile
		
		printf "\n<table border=\"1\">" >> $oFile
			printf "\n<caption>%s</caption>" "$title" >> $oFile
			printf "\n<tr>" >> $oFile
			printf "\n\t<th>Reference</th>" >> $oFile
			printf "\n\t<th>Text</th>" >> $oFile
			printf "\n\t</tr>" >> $oFile
			makeRow "$verse1Ref" "$verse1Text" "$oFile"
			makeRow "$verse2Ref" "$verse2Text" "$oFile"
			makeRow "$verse3Ref" "$verse3Text" "$oFile"
			makeRow "$verse4Ref" "$verse4Text" "$oFile"
			makeRow "$verse5Ref" "$verse5Text" "$oFile"
			printf "\n</table>" >> $oFile
		printf "\n<hr>" >> $oFile
		
		printf "\n<table border=\"1\">" >> $oFile
			printf "\n<caption>%s</caption>" "$title" >> $oFile
			printf "\n<tr>" >> $oFile
			printf "\n\t<th>Reference</th>" >> $oFile
			printf "\n\t<th>Text</th>" >> $oFile
			printf "\n\t</tr>" >> $oFile
			makeRow "$verse1Ref" "$verse1Text" "$oFile"
			makeRow "$verse2Ref" "$verse2Text" "$oFile"
			makeRow "$verse3Ref" "$verse3Text" "$oFile"
			makeRow "$verse4Ref" "$verse4Text" "$oFile"
			makeRow "$verse5Ref" "$verse5Text" "$oFile"
			printf "\n</table>" >> $oFile

		printf "\n</body></html>" >> $oFile

		;;
		"sp") #Catch some typos, spelling errors. Uncertain best among several spell checkers, aspell, hunspell, etc. Just pick one
			hunspell $oFile #othr spell checkers - aspell, etc.
			;;

      "uc") #check for unicode
	  	#unicode may have lots of benefits, but some legacy software tools that only do ASCII might crash if reading a unicode.
		#For example, ascii tools my want straight quotes and not curly quotes.
        grep -rnoP "[^\x00-\x7F]" "$oFile" #n option for line number
	  ;;
		*)
			printf 'unexpected argument %s, plz try again' "$1"
			exit 1
			;;
	esac
 	exit 0
 } #end details


makeRow() {
	printf "\n<tr>" >> $oFile
		printf "\n\t<td>%s</td>" "$1" >> "$3"
		printf "\n\t<td>%s</td>" "$2" >> "$3"
		printf "\n\t</tr>" >> $oFile
}

main "$@"; exit

